/*Given two strings s and t which consist of only lowercase letters.
 String t is generated by random shuffling string s and then add
 one more letter at a random position.Find the letter that was added in t.*/

#include "finddifference.h"
#include <unordered_map>
#include <iostream>

/*template<class T, class K>
 K finddifference<T,K>::findoneletterdifference(T &s, T &r)
 {
 if(s.size() + 1 != r.size()) return ' ';

 std::unordered_map<K, int> map;

 for(K c : s) ++map[c];
 for(K c : r) {
 --map[c];
 if(map[c] < 0) return c;
 }

 return ' ';
 }*/
